model: 'ResNet_RetinaNet'
dataset_name: 'Pascal'
classes: 20
in_channels: 3
train_list: '/mnt/voc_train/train_list.txt'
val_list: '/mnt/voc_train/val_list.txt'
names: '/dataset/detection/names/pascal_voc.txt'
input_size: 320

workers: 4
epochs: 500
batch_size: 10

save_freq: 1
save_dir: './saved'
gpus : 0

# model Define
backbone: 'ResNet'
fpn: 'default'
cls_subnet: 'default'
reg_subnet: 'default'

optimizer: 'sgd'
optimizer_options:
  lr: 1e-3
  momentum: 0.9


cls_loss: 'focal_loss'
reg_loss: 'ciou_loss'

trainer_options:
  check_val_every_n_epoch: 5

experimental_options:
  os: 'windows'
  callbacks:
    - 'SWA'
